services:
  requirement_list:
    build: .
    image: ghcr.io/bteam-toku/requirement_list:latest
    container_name: requirement_list_container
    environment:
      - IS_DOCKER=true
    volumes:
      - .:/data
      - ./customizes:/app/src/requirement_list/customizes
