#
# 設定ファイルのサンプルです。
# 設定情報を更新のうえ、settings.yamlにRenameして使用してください。
#

# -- Adapter指定 ---
adapter_type_name: ""  # デフォルトアダプターを指定

# -- 要件リスト（EXCEL)設定 ---
excel_settings:
  book_name: "your_requirement_filename.xlsx"
  column_id: "id"
  column_title: "title"

# --- パス設定 ---
# プロジェクトルートディレクトリからの相対パスで指定。Docker環境では /data 以下にマウントされます。
path_settings:
  input_path: "input"
  output_path: "output"
